---
- name: List agents currently labeled with the cluster order label
  kubernetes.core.k8s_info:
    kind: Agent
    api_version: agent-install.openshift.io/v1beta1
    namespace: "{{ default_agent_namespace }}"
    label_selectors:
      - "{{ cluster_order_label }}={{ manage_agents_cluster_order_name }}"
  register: manage_agents_allocated

- name: List agents removed from the cluster
  ansible.builtin.set_fact:
    manage_agents_removed: >
      {{ manage_agents_allocated.resources | selectattr('spec.clusterDeploymentName.name', 'undefined') }}

- name: Move agents to idle agents network
  ansible.builtin.include_role:
    name: massopencloud.esi.l2
    tasks_from: set_networks_for_node
  vars:
    node: "{{ agent.metadata.annotations['esi.nerc.mghpcc.org/uuid'] }}"
    networks:
    - "{{ manage_agents_idle_agents_network }}"
  loop: "{{ manage_agents_removed }}"
  loop_control:
    label: "Detach agent {{ agent.metadata.name }}"
    loop_var: agent

- name: Un-label agents
  kubernetes.core.k8s_json_patch:
    api_version: agent-install.openshift.io/v1beta1
    kind: Agent
    name: "{{ agent.metadata.name }}"
    namespace: "{{ default_agent_namespace }}"
    patch:
      - op: remove
        path: /metadata/labels/{{ cluster_order_label | cloudkit.service.json_pointer_escape }}
      - op: remove
        path: /metadata/labels/agentMachineRef
  loop: "{{ manage_agents_removed }}"
  loop_control:
    loop_var: agent
    label: "Un-label agent {{ agent.metadata.name }}"
  register: manage_agents_removed_result
