---
- name: Create cert-manager subscription
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
          name: cert-manager
      spec:
          channel: stable
          installPlanApproval: Automatic
          name: cert-manager
          source: community-operators
          sourceNamespace: openshift-marketplace

- name: Create production issuer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-production-dns01
      spec:
        acme:
          email: help@nerc.mghpcc.org
          privateKeySecretRef:
            name: letsencrypt-production-key
          server: https://acme-v02.api.letsencrypt.org/directory
          solvers:
          - dns01:
              cnameStrategy: Follow
              route53:
                region: us-east-1
                accessKeyIDSecretRef:
                  key: AWS_ACCESS_KEY_ID
                  name: aws-route53-credentials
                secretAccessKeySecretRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: aws-route53-credentials
  register: production_issuer_result
  until: production_issuer_result is succeeded
  retries: 30
  delay: 10

- name: Create staging issuer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-staging-dns01
      spec:
        acme:
          email: help@nerc.mghpcc.org
          privateKeySecretRef:
            name: letsencrypt-staging-key
          server: https://acme-staging-v02.api.letsencrypt.org/directory
          solvers:
          - dns01:
              cnameStrategy: Follow
              route53:
                region: us-east-1
                accessKeyIDSecretRef:
                  key: AWS_ACCESS_KEY_ID
                  name: aws-route53-credentials
                secretAccessKeySecretRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: aws-route53-credentials
  register: staging_issuer_result
  until: staging_issuer_result is succeeded
  retries: 30
  delay: 10
